# 1. Create a 3x3x3 array with random values 

In [6]:
import numpy as np
a = np.random.uniform((3,3,3))
print(a)

[2.50210659 1.90990581 2.33482428]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [8]:
b = np.diag(1+np.arange(4),k=-1)
print(b)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [10]:
c = np.zeros((8,8),dtype=int)
c[1::2 , ::2] = 1
c[::2 , 1::2] = 1
print(c)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [13]:
d = np.random.random((5,5))
dmax,dmin = d.max(),d.min()
d = (d-dmin)/(dmax-dmin)
print(d)

[[0.022166   0.68000214 0.         0.81071015 0.53843487]
 [0.66608225 0.81623263 0.08461412 0.82463767 0.75629329]
 [0.36840592 0.49796497 0.84001585 0.36512621 0.55967508]
 [0.37285334 0.85068566 0.60018667 1.         0.98592077]
 [0.16327482 0.80284329 0.44834273 0.70216039 0.74822211]]


# 5.  How to find common values between two arrays?

In [1]:
import numpy as np
array1 = np.array([1, 2, 3 , 4, 5, 6])
print("Array1 is : ",array1)
array2 = [5,6,7,8,9]
print("Array2 is : ",array2)
print("Common values between two arrays are :")
print(np.intersect1d(array1, array2))

Array1 is :  [1 2 3 4 5 6]
Array2 is :  [5, 6, 7, 8, 9]
Common values between two arrays are :
[5 6]


# 6.How to get the dates of yesterday, today and tomorrow?

In [2]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday's date is : ",yesterday)
today     = np.datetime64('today', 'D')
print("Today's date is : ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow's date is : ",tomorrow)

Yestraday's date is :  2020-07-27
Today's date is :  2020-07-28
Tomorrow's date is :  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [22]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

print(A)
print(B)
equal = np.allclose(A,B)
print(equal)

[1 1 0 0 1]
[1 1 1 1 0]
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [3]:
a = np.random.random(10)
print("Original array is :")
print(a)
a[a.argmax()] = 0
print("Maximum value replaced by 0 : ")
print(a)

Original array is :
[0.99505024 0.34110925 0.5388899  0.25958937 0.72464723 0.53828989
 0.51745112 0.02640986 0.50015593 0.30004054]
Maximum value replaced by 0 : 
[0.         0.34110925 0.5388899  0.25958937 0.72464723 0.53828989
 0.51745112 0.02640986 0.50015593 0.30004054]


# 9. How to print all the values of an array?

In [4]:
array1 = np.arange(10)
print("All values of an array are as follows ")
print(array1)

All values of an array are as follows 
[0 1 2 3 4 5 6 7 8 9]


# 10.Subtract the mean of each row of a matrix

In [26]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)
Y

array([[-0.41184634, -0.05169548,  0.04380243,  0.29017999,  0.11901999,
         0.22346101, -0.17030638,  0.18102875, -0.26892318,  0.04527921],
       [-0.30459089,  0.31118029, -0.18988153,  0.37614553, -0.1678965 ,
         0.35506636,  0.29555296, -0.1054991 , -0.12490211, -0.44517501],
       [ 0.40403975, -0.24003935,  0.0678398 ,  0.07609439, -0.36533546,
         0.03045546, -0.08319553, -0.26149113,  0.33522892,  0.03640315],
       [ 0.32921551, -0.36567348,  0.24497614,  0.00719278,  0.37705482,
        -0.52252631,  0.09962297,  0.12299996, -0.14972714, -0.14313526],
       [-0.10652825, -0.37478213, -0.22443513,  0.1422279 ,  0.19245436,
        -0.02995828,  0.22613599,  0.37213088,  0.10998905, -0.30723438]])

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [28]:
ZZ = np.ones(10)
I = np.random.randint(0,len(ZZ),20)
ZZ += np.bincount(I, minlength=len(ZZ))
print(ZZ)

[4. 1. 1. 2. 2. 4. 5. 4. 3. 4.]


# 12.How to get the diagonal of a dot product?

In [29]:
A = np.random.randint(0,10,(3,3))
B= np.random.randint(0,10,(3,3))
#Slow version

np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([16, 81, 14])

# 13.How to find the most frequent value in an array?

In [30]:
Z = np.random.randint(0,10,50)
print (Z)
print('rank:', np.bincount(Z).argmax())

[6 8 5 6 7 0 3 9 3 4 7 9 7 7 7 1 9 0 9 3 4 7 2 5 7 8 6 9 6 4 1 1 6 7 4 2 8
 1 6 3 7 2 0 9 5 5 3 9 7 0]
rank: 7


# 14.How to get the n largest values of an array

In [20]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
#print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [17]:
rec_array = np.array([("Hello",2.5,3),("World",3.6,2)])
rec_array1 = np.core.records.fromarrays(rec_array.T,names="col1, col2, col3",formats = "S8, f8, i8")

#Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
#R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(rec_array)
print(rec_array1)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
